"""Delivery module — Discord webhook + Dropzone SCP for prompt delivery."""

import subprocess
import tempfile
from pathlib import Path

import requests

from config import COS_DISCORD_WEBHOOK, DROPZONE_SCP_TARGET, DROPZONE_SSH_KEY, log


def deliver_to_discord(title: str, content: str) -> bool:
    """POST a message to #chief-of-staff webhook. Truncates to Discord's 2000-char limit."""
    if not COS_DISCORD_WEBHOOK:
        log("  Warning: COS_DISCORD_WEBHOOK not configured — skipping Discord delivery")
        return False

    message = content
    if len(message) > 1900:
        message = message[:1900] + f"\n\n*Truncated — full prompt on Dropzone*"

    payload = {"content": f"**{title}**\n\n{message}"}
    # Discord webhook payload limit is on the content field (2000 chars)
    if len(payload["content"]) > 2000:
        payload["content"] = payload["content"][:1997] + "..."

    try:
        resp = requests.post(COS_DISCORD_WEBHOOK, json=payload, timeout=10)
        if resp.status_code in (200, 204):
            log(f"  Delivered to Discord: {title}")
            return True
        else:
            log(f"  Warning: Discord webhook returned {resp.status_code}")
            return False
    except requests.RequestException as exc:
        log(f"  Warning: Could not deliver to Discord: {exc}")
        return False


def wrap_prompt_html(title: str, prompt_text: str) -> str:
    """Generate an HTML page with the prompt in a styled pre block + copy button."""
    escaped_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    escaped_prompt = prompt_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{escaped_title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 900px; margin: 2rem auto; padding: 0 1rem;
         background: #1a1a2e; color: #e0e0e0; }}
  h1 {{ color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 0.5rem; }}
  .prompt-container {{ position: relative; margin-top: 1rem; }}
  pre {{ background: #16213e; border: 1px solid #0f3460; border-radius: 8px;
         padding: 1.5rem; overflow-x: auto; white-space: pre-wrap;
         word-wrap: break-word; line-height: 1.6; font-size: 0.9rem; }}
  .copy-btn {{ position: absolute; top: 0.5rem; right: 0.5rem;
               background: #00d4ff; color: #1a1a2e; border: none;
               padding: 0.4rem 1rem; border-radius: 4px; cursor: pointer;
               font-weight: bold; font-size: 0.85rem; }}
  .copy-btn:hover {{ background: #00b8d4; }}
  .meta {{ color: #888; font-size: 0.85rem; margin-top: 1rem; }}
</style>
</head>
<body>
<h1>{escaped_title}</h1>
<div class="prompt-container">
  <button class="copy-btn" onclick="copyPrompt()">Copy</button>
  <pre id="prompt-text">{escaped_prompt}</pre>
</div>
<p class="meta">Generated by Intake Pipeline &mdash; Phase 2 Prompt Builder</p>
<script>
function copyPrompt() {{
  const text = document.getElementById('prompt-text').textContent;
  navigator.clipboard.writeText(text).then(() => {{
    const btn = document.querySelector('.copy-btn');
    btn.textContent = 'Copied!';
    setTimeout(() => btn.textContent = 'Copy', 2000);
  }});
}}
</script>
</body>
</html>"""


def deliver_to_dropzone(filename: str, content: str) -> bool:
    """Write content to a temp file and SCP to the Dropzone server."""
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=f"_{filename}", delete=False,
                                         encoding="utf-8") as f:
            f.write(content)
            tmp_path = f.name

        cmd = [
            "scp", "-O",
            "-i", DROPZONE_SSH_KEY,
            "-o", "StrictHostKeyChecking=no",
            tmp_path,
            f"{DROPZONE_SCP_TARGET}{filename}",
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        # Clean up temp file
        Path(tmp_path).unlink(missing_ok=True)

        if result.returncode == 0:
            log(f"  Delivered to Dropzone: {filename}")
            return True
        else:
            log(f"  Warning: SCP failed: {result.stderr.strip()}")
            return False
    except Exception as exc:
        log(f"  Warning: Could not deliver to Dropzone: {exc}")
        return False


def deliver_prompt(title: str, prompt_text: str) -> dict:
    """Build HTML, push to Discord + Dropzone. Returns status dict."""
    safe_name = "".join(c if c.isalnum() or c in "-_" else "-" for c in title.lower())
    filename = f"prompt-{safe_name}.html"

    html = wrap_prompt_html(title, prompt_text)

    discord_ok = deliver_to_discord(
        f"Prompt Ready: {title}",
        f"```\n{prompt_text[:1500]}\n```\n\nFull prompt on Dropzone: `{filename}`"
    )
    dropzone_ok = deliver_to_dropzone(filename, html)

    return {
        "title": title,
        "filename": filename,
        "discord": discord_ok,
        "dropzone": dropzone_ok,
    }
